### ISSUE TITLE
Attempting to run IK on a model without markers, then trying to open the Plotter crashes GUI

### ISSUE THREAD

**Issue by carmichaelong** [opensim-org/opensim-gui#1004]
### Steps to reproduce
1. Open gait2392_simbody.osim
2. Open IK tool
3. Load subject01_Setup_IK.xml
4. Click "Run", then close the dialog box.
5. Click on Tools --> Plot

### Expected result
Plotter window shows up

### Actual result
GUI crashes, window disappears and no error log is generated.

### Environment and GUI version
W10 OpenSim 4.0-2018-09-19-14410c3d, originally found while testing #983

**Comment by aymanhab** [comment]
This boils down to InverseKinematicsSolver adding a Kinematics analysis to the model that lives on the stack that goes out of scope but is not deleted when the exception is thrown, leaving the model stuck with a stale pointer.

**Comment by aymanhab** [comment]
Fixed on opensim-core side, PR https://github.com/opensim-org/opensim-core/pull/2354

**Comment by carmichaelong** [comment]
Still have the same behavior on W10 Pro using OpenSim 4.0-2018-11-05-7253fe33. Is forcing an update on AppVeyor not working as intended?

**Comment by carmichaelong** [comment]
Ah, that makes sense. Definitely forgot to check if core built correctly. Thanks @chrisdembia
