### ISSUE TITLE
Running Scale Tool fails on mac due to trying to write files to root (working) directory

### ISSUE THREAD

**Issue by jenhicks** [opensim-org/opensim-gui#401]
Related issue on opensim-core:
https://github.com/opensim-org/opensim-core/issues/1957

**Comment by aymanhab** [comment]
ModelScaler methods addScale, addMeasurement do not communicate transfer of ownership across interface causing carshes downstream. Same with MarkrePairSet. Need to fix in SWIG interface files. Where do we place these @chrisdembia so they serve both python, java

**Comment by chrisdembia** [comment]
@aymanhab we have not handled this in the shared interface files. In the past, we handled this separately for each language.

For Python, we can use the handy `%pythonappend` construct. I'm not sure if something like that is available for Java.

**Comment by bspineda** [comment]
I came across the same issue when testing on the Mac build - OpenSim-4.0.Beta_0930_Mac.pkg.

**Comment by aymanhab** [comment]
Issue causing crash has been fixed. Issue related to writing spurious files lives on API side, issue open as indicated above.

**Comment by bspineda** [comment]
The scaling issue still shows on the MAC for the latest build. Nothing happens when you do the scaling.

**Comment by tkuchida** [comment]
@aymanhab https://github.com/opensim-org/opensim-core/issues/1957 (indicated above) has been closed; should it be reopened?

**Comment by aymanhab** [comment]
Yes it should be reopened. We need to decide behavior if files are specified in xml or else why the failure on osx.
